name: tests

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  tests:
    name: tests
    strategy:
      matrix:
        pyver: ["3.8", "3.9", "3.10"]

    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.pyver }}
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda install --quiet \
            pip \
            setuptools \
            numpy \
            flake8 \
            pytest \
            pytest-cov \
            sep

          python -m pip install -e .

      - name: lint
        shell: bash -l {0}
        run: |
          flake8 sxdes

      - name: test
        shell: bash -l {0}
        run: |
          pytest -v --cov=sxdes --cov-report term-missing sxdes
